{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-tally.tierName" (dict "ctx" . "tier" "gateway") }}
  labels:
    {{- include "ai-tally.labels" . | nindent 4 }}
    {{- include "ai-tally.selectorLabels" (dict "ctx" . "tier" "gateway") | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-tally.selectorLabels" (dict "ctx" . "tier" "gateway") | nindent 4 }}
{{- end }}
