-- Storage tiering & TTL reference (ai-tally telemetry store)
-- Implements CTO-29. Spec §5.1, Appendix A.
--
-- This file documents the tiering contract. The authoritative TTL clause lives on otel_spans
-- (otel_spans.sql) and is GENERATED from tally.storage_tiering.DEFAULT_POLICY.render_ttl_clause(),
-- the single source of truth that ALSO classifies a span's tier at query time. Keeping generation
-- and classification in one Python module means the table DDL and the runtime logic can't drift.
--
-- Tier ladder (default policy):
--   age <  7d  -> HOT      (fast SSD volume, full row-granular queries)
--   age <  30d -> WARM     (cheaper volume; last-month deep dives)
--   age <  90d -> COLD     (object-store-backed volume; rare late true-ups)
--   age >= 90d -> AGGREGATE (raw row dropped; only daily_feature_rollup survives)
--
-- The storage policy below names the 'warm'/'cold' volumes the TTL MOVE clauses target. Disk paths
-- and the actual mounts are infra (ClickHouse Cloud storage policy, CTO-94); shown here for shape.

-- Example storage policy (configured cluster-side, not applied by migrations):
--
--   <storage_configuration>
--     <disks>
--       <hot><path>/var/lib/clickhouse/hot/</path></hot>
--       <warm><path>/mnt/warm/</path></warm>
--       <cold><type>s3</type><endpoint>...</endpoint></cold>   <!-- CTO-28 object storage -->
--     </disks>
--     <policies>
--       <tiered>
--         <volumes>
--           <hot><disk>hot</disk></hot>
--           <warm><disk>warm</disk></warm>
--           <cold><disk>cold</disk></cold>
--         </volumes>
--       </tiered>
--     </policies>
--   </storage_configuration>
--
-- otel_spans then sets `SETTINGS storage_policy = 'tiered'` (applied with the volume mounts, infra).

-- ---------------------------------------------------------------------------------------------- --
-- Surviving aggregate after raw-drop.
-- daily_feature_rollup (rollups.sql, CTO-24) is keyed by (TenantId, FeatureTag, Day,
-- GenAiResponseModel) — exactly tally.storage_tiering.WARM_AGGREGATE_DIMENSIONS. Because the MV
-- writes on ingest (independent of otel_spans' TTL), the per-(tenant, feature, day, model) sums
-- needed for trends + reconciliation remain queryable long after the 90d raw horizon. Verify with:
--
--   -- raw span gone after 90d:
--   SELECT count() FROM otel_spans
--   WHERE TenantId = {t} AND Timestamp < now() - INTERVAL 90 DAY;   -- expect 0
--   -- aggregate still present:
--   SELECT sum(EstimatedCost) FROM daily_feature_rollup
--   WHERE TenantId = {t} AND Day < today() - 90;                    -- expect > 0

-- ---------------------------------------------------------------------------------------------- --
-- Per-tenant retention override (enterprise = longer raw retention).
-- ClickHouse TTL is table-level, so an override can't be a separate clause — the raw-drop interval
-- is compiled into a multiIf on TenantId by
-- tally.storage_tiering.render_tenant_ttl_delete_expression(store). With an 'ent' tenant kept 365d
-- and an 'alpha' tenant kept 180d over the default 90d, the generated DELETE clause is:
--
--   ALTER TABLE otel_spans MODIFY TTL
--       toDateTime(Timestamp) + INTERVAL 7 DAY  TO VOLUME 'warm',
--       toDateTime(Timestamp) + INTERVAL 30 DAY TO VOLUME 'cold',
--       toDateTime(Timestamp) + multiIf(
--           TenantId = 'alpha', INTERVAL 180 DAY,
--           TenantId = 'ent',   INTERVAL 365 DAY,
--           INTERVAL 90 DAY) DELETE;

-- ---------------------------------------------------------------------------------------------- --
-- DERIVED-TABLE RETENTION (CTO-338)
-- ---------------------------------------------------------------------------------------------- --
-- Everything above concerns otel_spans. Nothing DERIVED from it had any retention at all, which is
-- how the three largest tables in the database came to be derived and unmanaged, each of them
-- bigger than the raw span table they came from. Measured on a 1.54M-span local stack:
--
--   last_touch_index  89.3 MiB  |  business_events  69.3 MiB  |  replay_samples  53.8 MiB
--   ...against otel_spans, the one table that WAS managed, at 49.0 MiB.
--
-- The policy is defined in tally.storage_tiering (DERIVED_TABLE_RETENTION), the same module that
-- generates the raw-span TTL above, for the same reason: one place, or they drift. Each table's TTL
-- is declared inline in its CREATE TABLE, and sdk/python/tests/test_derived_retention_ddl.py fails
-- if a DDL file and the module disagree about a horizon.
--
-- Four classes, longest first. The class is the argument; the number is downstream of it.
--
--   CLASS                 DAYS   TABLES                          WHY
--   book of record        2555   daily_feature_rollup            money that cannot be re-derived
--                                daily_account_rollup            once raw spans age out. 7 years is
--                                business_events                 the books-and-records horizon, and
--                                attribution_records             these are the books.
--   operational grain      400   hourly_feature_rollup           a finer or supporting copy of what
--                                identity_graph                  class 1 already holds. Losing it
--                                unattributed_events             costs resolution, never a total.
--                                eval_runs                       13 months = same month, last year.
--   follows raw spans       90   last_touch_index                pointers into otel_spans, and the
--                                business_events.RawPayload      raw artifact behind a mapped event.
--                                (column TTL: row survives)      Meaningless once the span is gone.
--   opt-in replay corpus    30   replay_samples                  NOT our number: it is the default
--                                replay_runs                     of tenant_replay_config.
--                                                                retention_days, already disclosed
--                                                                to the tenant in the opt-in
--                                                                consent text and never enforced.
--
-- These are delete-only TTLs, not the hot/warm/cold ladder. The ladder exists to keep bulky raw
-- spans queryable on cheap disk; these tables are small per row of answer and are read at
-- interactive latency, so tiering them would buy little and cost query time.
--
-- RELATIONSHIPS THE NUMBERS HAVE TO EACH OTHER, asserted in storage_tiering._validate_retention_
-- ladder() rather than left as prose here:
--
--   * last_touch_index == the raw span horizon, exactly. A per-tenant raw-retention override needs
--     the SAME override on last_touch_index, compiled into the same multiIf, or stitching for that
--     tenant silently reads a truncated index.
--   * attribution_records == business_events, exactly, in both directions. Shorter and attributed
--     revenue reads back as unattributed; longer and an attribution outlives its event.
--   * every rollup > the raw span horizon, or checks/rollup_drift.sql reads the missing rollup rows
--     as drift and the CTO-311 rebuild tries to repair a gap that is not one.
--   * business_events and attribution_records >> the dashboard's longest selectable window
--     (web/lib/explore.ts MAX_WINDOW_DAYS = 366). This one is a honesty constraint, not a cost one:
--     several revenue and ROI reads take a user-selectable range up to that length and at least one
--     KPI is unbounded, and their empty-result branches cannot currently distinguish "expired" from
--     "never happened" (an empty business_events renders attribution rate as 100%). The horizon is
--     therefore set where no read can reach it.
--   * replay_runs <= replay_samples. replay_runs holds ResponseText, a real model response body
--     under the CTO-125 carve-out; it must not outlive the retention the tenant consented to.
--
-- PER-TENANT OVERRIDES use exactly the mechanism raw spans use, via the shared primitive
-- render_tenant_delete_expression:
--
--   ALTER TABLE replay_samples MODIFY TTL
--       toDateTime(CapturedAt) + multiIf(
--           TenantId = 'alpha', INTERVAL 7 DAY,
--           TenantId = 'ent',   INTERVAL 90 DAY,
--           INTERVAL 30 DAY) DELETE;
--
-- APPLYING ANY OF THIS TO A POPULATED TABLE IS NOT FREE, and is deliberately not part of
-- `make ch-migrate`. See db/clickhouse/migrations/derived_table_retention.sql and
-- `make ch-apply-retention`: ClickHouse's materialize_ttl_after_modify defaults to 1, so a bare
-- MODIFY TTL mass-deletes on the spot.
