# SPDX-License-Identifier: Apache-2.0
#
# Data stores and secret containers (CTO-335): KMS, ECR, S3 replay bucket, RDS Postgres, and the
# Secrets Manager entries the task definitions reference by ARN.
#
# THE RULE THIS MODULE IS BUILT AROUND: no secret material enters Terraform state.
#
# State lives in an S3 bucket and is readable by anyone who can read that bucket. Terraform has no
# write-only attribute for a secret value, so any `aws_secretsmanager_secret_version` with a
# `secret_string` puts that string in state in cleartext, forever, including in every historical
# version of the object. That would turn CLAUDE.md's credentials-by-reference invariant into a
# statement about the database only, which is not what it says.
#
# So the boundary is drawn three ways:
#
#   1. Terraform creates the secret CONTAINER (name, KMS key, recovery window, tags) and outputs its
#      ARN. It never creates a version. The operator writes the value once with
#      `aws secretsmanager put-secret-value`, and it passes through their shell, not through state.
#      An empty container is honest: the task fails to start with a clear Secrets Manager error
#      rather than booting with a placeholder that looks like a real credential.
#   2. The RDS master password is never generated by Terraform at all.
#      `manage_master_user_password = true` makes RDS mint and rotate it into a Secrets Manager
#      secret RDS owns. The alternative, `random_password`, writes the password into state by
#      construction, which is the same failure wearing a helpful hat.
#   3. Per-tenant HMAC keys are NOT Terraform's. PR #352's `SecretManagerKeyProvider` mints one
#      secret per tenant under `ai-tally/tenant-hmac/<uuid>` at provision time, holds 32 bytes it
#      generated in memory, and stores only the ARN plus a `v1` staging label in
#      `tenants.hash_salt_kek_ref`. Terraform must never manage anything under that prefix: a
#      resource there would be seen as drift on the next plan and destroyed, and destroying a
#      tenant's HMAC key silently invalidates every hash ever computed for them. Terraform owns the
#      KMS key those secrets can be encrypted with, and the IAM grant on the prefix (see the iam
#      module), and nothing else. That is the whole seam, and it is why the two do not fight.

locals {
  ecr_repositories = ["${var.repository_namespace}/gateway", "${var.repository_namespace}/edge-proxy", "${var.repository_namespace}/web"]

  # Names, not values. Each becomes an empty container whose ARN the task definitions consume.
  # The two provider keys are optional: the gateway boots fail-soft without them (CTO-109).
  secret_names = concat(
    [
      "${var.name_prefix}-postgres-dsn",
      "${var.name_prefix}-clickhouse-password",
      "${var.name_prefix}-gateway-service-token",
    ],
    var.create_provider_key_secrets ? [
      "${var.name_prefix}-openai-api-key",
      "${var.name_prefix}-anthropic-api-key",
    ] : []
  )
}

# ---------------------------------------------------------------------------------------------
# KMS
# ---------------------------------------------------------------------------------------------

# One customer-managed key for Secrets Manager, RDS storage and the replay bucket. A CMK is what
# makes the `kms:ViaService` conditions in the two IAM policy documents meaningful: without it those
# statements name a key that does not exist, and deploy/aws/README.md section 6 tells the operator
# to delete them instead. Set create_kms_key = false to take that path.
resource "aws_kms_key" "this" {
  count = var.create_kms_key ? 1 : 0

  description             = "ai-tally: Secrets Manager, RDS storage and replay bucket encryption"
  enable_key_rotation     = true
  deletion_window_in_days = 30

  tags = var.tags
}

resource "aws_kms_alias" "this" {
  count = var.create_kms_key ? 1 : 0

  name          = "alias/${var.name_prefix}"
  target_key_id = aws_kms_key.this[0].key_id
}

locals {
  kms_key_arn = var.create_kms_key ? aws_kms_key.this[0].arn : null
  kms_key_id  = var.create_kms_key ? aws_kms_key.this[0].key_id : null
}

# ---------------------------------------------------------------------------------------------
# ECR
# ---------------------------------------------------------------------------------------------

resource "aws_ecr_repository" "this" {
  for_each = toset(local.ecr_repositories)

  name = each.value

  # MUTABLE, and it has to be. checkov's CKV_AWS_51 asks for IMMUTABLE, but the workflow PR #351
  # added publishes a moving `main` tag alongside the commit SHA, so an immutable repository would
  # fail every merge after the first. The tag a deployment pins is the SHA, which cannot move
  # anyway; that is the property immutability is there to buy.
  image_tag_mutability = "MUTABLE"

  # PR #351 tags by commit SHA and pushes on merge, so a scan on push is the only place a base-image
  # CVE gets noticed without a separate scanner.
  image_scanning_configuration {
    scan_on_push = true
  }

  encryption_configuration {
    encryption_type = var.create_kms_key ? "KMS" : "AES256"
    kms_key         = local.kms_key_arn
  }

  tags = var.tags
}

# SHA-tagged images accumulate one per merge and are never referenced again once a service moves on.
# The meter is GB-month, so the policy is about a bill nobody is watching rather than about disk.
resource "aws_ecr_lifecycle_policy" "this" {
  for_each = aws_ecr_repository.this

  repository = each.value.name
  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Expire untagged images after ${var.ecr_untagged_expiry_days} days"
      selection = {
        tagStatus   = "untagged"
        countType   = "sinceImagePushed"
        countUnit   = "days"
        countNumber = var.ecr_untagged_expiry_days
      }
      action = { type = "expire" }
      }, {
      rulePriority = 2
      description  = "Keep the newest ${var.ecr_image_count_limit} images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = var.ecr_image_count_limit
      }
      action = { type = "expire" }
    }]
  })
}

# ---------------------------------------------------------------------------------------------
# S3 replay bucket
# ---------------------------------------------------------------------------------------------

resource "aws_s3_bucket" "replay" {
  bucket = var.replay_bucket_name
  tags   = var.tags
}

resource "aws_s3_bucket_versioning" "replay" {
  bucket = aws_s3_bucket.replay.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "replay" {
  bucket = aws_s3_bucket.replay.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = var.create_kms_key ? "aws:kms" : "AES256"
      kms_master_key_id = local.kms_key_arn
    }
    bucket_key_enabled = var.create_kms_key
  }
}

resource "aws_s3_bucket_public_access_block" "replay" {
  bucket                  = aws_s3_bucket.replay.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# `S3ReplayBlobStore` deliberately does not expire its own objects, so the only thing standing
# between a sampled replay corpus and an unbounded GB-month meter is this rule. Versioning is on, so
# the noncurrent rule matters as much as the current one.
resource "aws_s3_bucket_lifecycle_configuration" "replay" {
  bucket = aws_s3_bucket.replay.id

  rule {
    id     = "expire-replay-bodies"
    status = "Enabled"

    filter {
      prefix = var.replay_prefix
    }

    expiration {
      days = var.replay_expiry_days
    }

    noncurrent_version_expiration {
      noncurrent_days = var.replay_noncurrent_expiry_days
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  # The rule above is scoped to the replay prefix, so an aborted multipart upload written anywhere
  # else in the bucket would never expire and would never appear in a listing either. This one
  # covers the whole bucket and does nothing except clean those up.
  rule {
    id     = "abort-incomplete-uploads-everywhere"
    status = "Enabled"

    filter {}

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

# ---------------------------------------------------------------------------------------------
# RDS
# ---------------------------------------------------------------------------------------------

resource "aws_db_subnet_group" "this" {
  name       = var.name_prefix
  subnet_ids = var.private_subnet_ids
  tags       = var.tags
}

resource "aws_db_parameter_group" "this" {
  # name_prefix, not name, and the pairing with create_before_destroy below is the whole reason
  # (CTO-361). A major engine upgrade changes `family`, which forces replacement. With a fixed name
  # and create_before_destroy, Terraform tries to CREATE the replacement before destroying the
  # original, both want the same name, and RDS answers DBParameterGroupAlreadyExists. The apply
  # then stops with a live database attached to a parameter group it is trying to replace, which is
  # the worst kind of stuck. name_prefix lets the new one exist alongside the old for the seconds
  # it takes to move the instance over.
  name_prefix = "${var.name_prefix}-postgres${split(".", var.db_engine_version)[0]}-"
  family      = "postgres${split(".", var.db_engine_version)[0]}"

  # The gateway's asyncpg pool speaks TLS already; this makes it non-optional at the server.
  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }

  tags = var.tags

  lifecycle {
    create_before_destroy = true
  }
}

# The same argument the compute module makes about the awslogs driver, applied to RDS.
# `enabled_cloudwatch_logs_exports` makes RDS create /aws/rds/instance/<id>/postgresql itself, with
# no retention, so it keeps every line forever at full price. Creating the group first with a
# retention means RDS finds one and uses it.
resource "aws_cloudwatch_log_group" "postgresql" {
  name              = "/aws/rds/instance/${var.name_prefix}-pg/postgresql"
  retention_in_days = var.db_log_retention_days
  tags              = var.tags
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-pg"
  engine         = "postgres"
  engine_version = var.db_engine_version
  instance_class = var.db_instance_class

  allocated_storage     = var.db_allocated_storage
  max_allocated_storage = var.db_max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = local.kms_key_arn

  db_name  = var.db_name
  username = var.db_master_username

  # See the header. RDS mints and holds the master password; it is never a Terraform value, never a
  # variable, and never in state. Its Secrets Manager ARN comes out as an output.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = local.kms_key_arn

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.rds_security_group_id]
  publicly_accessible    = false
  parameter_group_name   = aws_db_parameter_group.this.name

  multi_az                = var.db_multi_az
  backup_retention_period = var.db_backup_retention_days
  backup_window           = var.db_backup_window
  maintenance_window      = var.db_maintenance_window
  copy_tags_to_snapshot   = true

  auto_minor_version_upgrade = true
  deletion_protection        = var.db_deletion_protection
  skip_final_snapshot        = var.db_skip_final_snapshot
  final_snapshot_identifier  = var.db_skip_final_snapshot ? null : "${var.name_prefix}-pg-final-${var.environment}"

  performance_insights_enabled = var.db_performance_insights_enabled
  enabled_cloudwatch_logs_exports = [
    "postgresql",
  ]

  tags = var.tags

  # RDS creates the export log group on its own if it is not there, without a retention. Terraform
  # cannot see that through a string, so the edge is explicit.
  depends_on = [aws_cloudwatch_log_group.postgresql]
}

# ---------------------------------------------------------------------------------------------
# Secrets Manager containers, without values
# ---------------------------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "this" {
  for_each = toset(local.secret_names)

  name        = each.value
  description = "ai-tally deployment secret. Terraform owns the container; the value is written out of band. See deploy/aws/terraform/README.md."
  kms_key_id  = local.kms_key_id

  recovery_window_in_days = var.secret_recovery_window_days

  tags = var.tags
}

# Deliberately absent: aws_secretsmanager_secret_version. Adding one with a secret_string is how the
# value ends up in state. If a future change needs seeded values, the fix is an out-of-band writer,
# not this resource.
