#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Third-party license audit for ai-tally.
#
# Re-runnable from CI or locally. Writes a summary to docs/third-party-licenses.md.
# Flags GPL/AGPL/SSPL deps loudly so we can replace them before going public.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/docs/third-party-licenses.md"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "license-audit: writing report to $OUT"

# --- Python SDK -------------------------------------------------------------
PY_PROJ="${REPO_ROOT}/sdk/python"
PY_DEPS_NOTE="No runtime dependencies (per pyproject.toml). Dev-only: pytest, ruff."
if [ -f "${PY_PROJ}/pyproject.toml" ]; then
    if grep -qE '^dependencies\s*=\s*\[\s*\]' "${PY_PROJ}/pyproject.toml"; then
        :
    else
        PY_DEPS_NOTE="See sdk/python/pyproject.toml — runtime dependencies are non-empty; re-run audit."
    fi
fi

# --- Go edge-proxy ----------------------------------------------------------
GO_PROJ="${REPO_ROOT}/infra/edge-proxy"
GO_DEPS_NOTE="No third-party Go modules (stdlib only, per go.mod)."
if [ -f "${GO_PROJ}/go.sum" ]; then
    GO_DEPS_NOTE="See go.sum — third-party Go modules present; run go-licenses report ./..."
fi

# --- Web (Next.js) ----------------------------------------------------------
WEB_DIR="${REPO_ROOT}/web"
WEB_TABLE=""
WEB_FLAGS=""
if [ -d "${WEB_DIR}/node_modules" ]; then
    npx --yes license-checker --production --json --start "${WEB_DIR}" > "${TMPDIR}/web.json" 2>/dev/null
    python3 - "${TMPDIR}/web.json" > "${TMPDIR}/web-table.md" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
print("| Package | License | Repository |")
print("|---|---|---|")
for k, v in sorted(d.items()):
    lic = v.get("licenses", "?")
    repo = v.get("repository", "") or ""
    print(f"| `{k}` | {lic} | {repo} |")
PY
    WEB_TABLE="$(cat "${TMPDIR}/web-table.md")"

    # Flag copyleft.
    python3 - "${TMPDIR}/web.json" > "${TMPDIR}/web-flags.md" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
copyleft = ("GPL", "AGPL", "SSPL")
flagged = []
for k, v in d.items():
    lic = str(v.get("licenses", ""))
    if any(c in lic for c in copyleft):
        flagged.append((k, lic))
if flagged:
    for k, lic in flagged:
        print(f"- **{k}** — `{lic}`")
else:
    print("_None._")
PY
    WEB_FLAGS="$(cat "${TMPDIR}/web-flags.md")"
else
    WEB_TABLE="_node_modules not installed; run \`npm install\` in web/ then re-run this script._"
    WEB_FLAGS="_skipped (node_modules missing)_"
fi

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
<!--
SPDX-License-Identifier: Apache-2.0
Generated by scripts/license-audit.sh — do not edit by hand.
-->

# Third-party licenses

This file is regenerated by \`scripts/license-audit.sh\`. It catalogs the
runtime dependencies bundled with ai-tally components and flags any copyleft
licenses (GPL / AGPL / SSPL) that need attention before distribution.

## Python SDK (\`sdk/python\`)

${PY_DEPS_NOTE}

## Go edge-proxy (\`infra/edge-proxy\`)

${GO_DEPS_NOTE}

## Gateway (\`infra/gateway\`)

The gateway is a FastAPI application. Its runtime dependencies are documented
in its own \`pyproject.toml\` / requirements file once those land — this audit
will pick them up automatically.

## Web dashboard (\`web\`, production deps only)

${WEB_TABLE}

### Copyleft / restricted licenses

${WEB_FLAGS}

## Notes

- \`@img/sharp-libvips-*\` packages are LGPL-3.0-or-later. They ship the
  prebuilt libvips binary that \`sharp\` (the Next.js image optimizer)
  dynamically links to. LGPL dynamic linking is compatible with Apache-2.0
  distribution; we do not statically link libvips and we do not modify it.
  See <https://github.com/lovell/sharp> for the upstream licensing notes.
- \`caniuse-lite\` is CC-BY-4.0 (data, not code). Attribution lives in
  the project NOTICE file.
- \`ai-tally-web\` appears as \`UNLICENSED\` to license-checker because its
  \`package.json\` is marked \`private: true\`. The repository as a whole is
  Apache-2.0 (see \`LICENSE\`) and the web package declares
  \`"license": "Apache-2.0"\`.
EOF

echo "license-audit: done."
