# SPDX-License-Identifier: Apache-2.0
"""The derived-table retention policy (CTO-338) against the ClickHouse DDL that implements it.

``tally.storage_tiering`` is only a single source of truth if something fails when the DDL stops
agreeing with it. For the raw-span TTL that guarantee has always been implicit (one clause, one
table, generated by hand from ``render_ttl_clause``). Twelve horizons across six files is past the
point where a human notices a drift, so it is asserted here: every TTL in the policy must appear
verbatim in the CREATE TABLE that owns it, and in the migration that applies it to a live install.

No ClickHouse in CI, so this is textual. That is enough to catch the failure that actually happens,
which is somebody changing a number in one place.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tally.storage_tiering import (
    BOOK_OF_RECORD_DAYS,
    DASHBOARD_MAX_WINDOW_DAYS,
    DEFAULT_POLICY,
    DERIVED_TABLE_RETENTION,
    OPERATIONAL_GRAIN_DAYS,
    REPLAY_CORPUS_DAYS,
    SPAN_DERIVED_ROLLUPS,
    RetentionPolicy,
    render_tenant_delete_expression,
    retention_for,
)

REPO = Path(__file__).resolve().parents[3]
CH = REPO / "db" / "clickhouse"

# Which DDL file declares each table's CREATE TABLE.
DDL_FILE = {
    "daily_feature_rollup": "rollups.sql",
    "hourly_feature_rollup": "rollups.sql",
    "daily_account_rollup": "account_rollups.sql",
    "business_events": "attribution.sql",
    "attribution_records": "attribution.sql",
    "identity_graph": "attribution.sql",
    "unattributed_events": "attribution.sql",
    "last_touch_index": "last_touch_index.sql",
    "replay_samples": "replay_samples.sql",
    "replay_runs": "replay_samples.sql",
    "eval_runs": "eval_runs.sql",
}

MIGRATION = CH / "migrations" / "derived_table_retention.sql"


@pytest.fixture(scope="module")
def ddl_text() -> dict[str, str]:
    return {name: (CH / name).read_text() for name in sorted(set(DDL_FILE.values()))}


@pytest.fixture(scope="module")
def migration() -> str:
    assert MIGRATION.exists(), f"missing {MIGRATION}"
    return MIGRATION.read_text()


# --------------------------------------------------------------------------- #
# The policy is complete and self-describing
# --------------------------------------------------------------------------- #
def test_every_policy_carries_a_reason():
    for policy in DERIVED_TABLE_RETENTION:
        assert policy.rationale.strip(), f"{policy.table} has a horizon with no argument for it"


def test_every_managed_table_has_a_known_ddl_file():
    for policy in DERIVED_TABLE_RETENTION:
        assert policy.table in DDL_FILE, (
            f"{policy.table} is in the policy but no DDL file claims it"
        )


def test_retention_for_rejects_an_unmanaged_table():
    # An unmanaged derived table is the bug this ticket exists to fix, so the lookup raises rather
    # than quietly handing back a default that nobody chose.
    with pytest.raises(KeyError):
        retention_for("otel_spans")


# --------------------------------------------------------------------------- #
# The DDL says what the policy says
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("policy", DERIVED_TABLE_RETENTION, ids=lambda p: f"{p.table}.{p.column}")
def test_ddl_declares_the_policy_clause(policy: RetentionPolicy, ddl_text: dict[str, str]):
    text = ddl_text[DDL_FILE[policy.table]]
    if policy.column is not None:
        # Column TTL: declared inline on the column, so there is no DELETE keyword.
        expected = f"TTL toDateTime({policy.timestamp_column}) + INTERVAL {policy.days} DAY"
        assert expected in text, f"{policy.table}.{policy.column} missing column TTL {expected!r}"
    else:
        assert policy.render_ttl_clause() in text, (
            f"{DDL_FILE[policy.table]} does not declare {policy.render_ttl_clause()!r} "
            f"for {policy.table}"
        )


@pytest.mark.parametrize("policy", DERIVED_TABLE_RETENTION, ids=lambda p: f"{p.table}.{p.column}")
def test_migration_applies_the_policy(policy: RetentionPolicy, migration: str):
    assert policy.render_alter() in migration, (
        f"derived_table_retention.sql is missing {policy.render_alter()!r}. Regenerate it from "
        "tally.storage_tiering rather than editing the number in one place."
    )


def test_migration_disables_materialize_ttl_after_modify(migration: str):
    # The single most important line in that file. Without it every ALTER mass-deletes on the spot,
    # because ClickHouse defaults materialize_ttl_after_modify to 1.
    # Statements only. The header talks about ALTER at length, and a comment is not an ordering.
    statements = [
        ln.strip() for ln in migration.splitlines() if ln.strip() and not ln.startswith("--")
    ]
    assert "SET materialize_ttl_after_modify = 0;" in statements
    first_set = statements.index("SET materialize_ttl_after_modify = 0;")
    first_alter = next(i for i, ln in enumerate(statements) if ln.startswith("ALTER TABLE"))
    assert first_set < first_alter, "the ALTERs must not run before the setting that defuses them"


def test_rollup_rebuild_restores_the_rollup_ttls():
    # CREATE TABLE ... AS copies skipping indexes but NOT the TTL (CTO-245). The rebuild creates its
    # shadow rollups that way and then EXCHANGEs them in, so without an explicit restore it would
    # silently return all three rollups to unbounded growth.
    text = (CH / "migrations" / "rollup_rebuild_from_spans.sql").read_text()
    for table in SPAN_DERIVED_ROLLUPS:
        policy = retention_for(table)
        assert f"{table}_cto311  MODIFY TTL {policy.delete_expression()}" in text.replace(
            f"{table}_cto311 MODIFY TTL", f"{table}_cto311  MODIFY TTL"
        ), f"the rebuild does not restore {table}'s TTL onto its shadow table"


# --------------------------------------------------------------------------- #
# The relationships between the numbers
# --------------------------------------------------------------------------- #
def test_classes_are_ordered():
    assert REPLAY_CORPUS_DAYS < OPERATIONAL_GRAIN_DAYS < BOOK_OF_RECORD_DAYS


def test_last_touch_index_tracks_the_raw_span_horizon():
    # It is an index of pointers into otel_spans. Outliving the spans buys dangling pointers.
    assert retention_for("last_touch_index").days == DEFAULT_POLICY.cold_days


def test_attribution_and_revenue_expire_together():
    # Either direction is a wrong number: shorter turns paid-for revenue into unattributed revenue,
    # longer leaves an attribution explaining an event that no longer exists.
    assert retention_for("attribution_records").days == retention_for("business_events").days


def test_rollups_outlive_raw_spans():
    # checks/rollup_drift.sql re-derives these from otel_spans. A rollup that expired first would
    # read as drift the rebuild then tries to repair.
    for table in SPAN_DERIVED_ROLLUPS:
        assert retention_for(table).days > DEFAULT_POLICY.cold_days


def test_revenue_outlasts_the_longest_dashboard_window():
    # web/lib/explore.ts clamps to 366 days, and at least one revenue KPI is unbounded. Their
    # empty-result branches cannot yet distinguish "expired" from "never happened" (an empty
    # business_events renders attribution rate as 100%), so the horizon is put out of reach.
    for table in ("business_events", "attribution_records"):
        assert retention_for(table).days >= DASHBOARD_MAX_WINDOW_DAYS * 4


def test_replay_bodies_do_not_outlive_the_consented_corpus():
    # replay_runs.ResponseText is a real model response body under the CTO-125 carve-out.
    assert retention_for("replay_runs").days <= retention_for("replay_samples").days


def test_replay_horizon_matches_the_promise_already_made_in_postgres():
    # Not our number to invent: tenant_replay_config.retention_days already states it, and the
    # opt-in consent text quotes it back to the tenant.
    pg = (REPO / "db" / "postgres" / "0004_tenant_replay_config.sql").read_text()
    assert "retention_days   INTEGER NOT NULL DEFAULT 30" in pg
    assert retention_for("replay_samples").days == REPLAY_CORPUS_DAYS == 30


def test_business_events_row_outlives_its_raw_payload():
    # The whole point of the column TTL: the money stays for years, the verbatim webhook body does
    # not. Equal horizons would mean the split bought nothing.
    assert (
        retention_for("business_events", column="RawPayload").days
        < retention_for("business_events").days
    )


# --------------------------------------------------------------------------- #
# Per-tenant overrides use the same mechanism raw spans use
# --------------------------------------------------------------------------- #
def test_override_expression_is_deterministic_and_falls_back_to_the_default():
    expr = render_tenant_delete_expression(
        30, {"ent": 90, "alpha": 7}, timestamp_column="CapturedAt"
    )
    assert expr == (
        "toDateTime(CapturedAt) + multiIf("
        "TenantId = 'alpha', INTERVAL 7 DAY, "
        "TenantId = 'ent', INTERVAL 90 DAY, "
        "INTERVAL 30 DAY) DELETE"
    )


def test_policy_renders_its_own_override_alter():
    alter = retention_for("replay_samples").render_alter({"ent": 90})
    assert alter.startswith(
        "ALTER TABLE replay_samples MODIFY TTL toDateTime(CapturedAt) + multiIf"
    )
    assert alter.endswith("INTERVAL 30 DAY) DELETE;")


def test_column_policy_renders_a_modify_column_alter():
    alter = retention_for("business_events", column="RawPayload").render_alter()
    assert alter == (
        "ALTER TABLE business_events MODIFY COLUMN RawPayload String CODEC(ZSTD(3)) "
        "TTL toDateTime(OccurredAt) + INTERVAL 90 DAY;"
    )
    # A column TTL resets the column, it does not delete the row. DELETE here would be a real bug.
    assert "DELETE" not in alter


def test_bad_policies_are_rejected():
    with pytest.raises(ValueError):
        RetentionPolicy(table="t", timestamp_column="ts", days=0, rationale="x")
    with pytest.raises(ValueError):
        RetentionPolicy(table="t", timestamp_column="ts", days=30, rationale="")
    with pytest.raises(ValueError):
        # column and column_type only make sense together.
        RetentionPolicy(table="t", timestamp_column="ts", days=30, rationale="x", column="c")
